service: ecofriendly-backend
frameworkVersion: "4"

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-offline

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  stage: ${opt:stage,'local'}
  timeout: 10
  memorySize: 256
  environment:
    STAGE: ${self:provider.stage}
    CONFIG_PATH: "${self:service}/config.ini"
    JWT_SECRET: ${ssm:/ecofriendly/${self:provider.stage}/jwt_secret~true}

functions:
  auth:
    handler: src/interface/auth.handler
    events:
      - httpApi:
          path: /api/auth/login
          method: post

  users:
    handler: src/interface/users.handler
    events:
      - httpApi: { path: /api/users, method: post }
      - httpApi: { path: /api/users, method: get }

  bins:
    handler: src/interface/bins.handler
    events:
      - httpApi: { path: /api/bins, method: get }
      - httpApi: { path: /api/bins/{id}, method: put }

  vehicles:
    handler: src/interface/vehicles.handler
    events:
      - httpApi: { path: /api/vehicles, method: get }

  shifts:
    handler: src/interface/shifts.handler
    events:
      - httpApi: { path: /api/shifts, method: post }

  payroll:
    handler: src/interface/payroll.handler
    events:
      - httpApi: { path: /api/payroll, method: get }

  reports:
    handler: src/interface/reports.handler
    events:
      - httpApi: { path: /api/reports/{type}, method: get }

  hwSimulator:
    handler: src/hw_sim/handler.handler
    events:
      - schedule: rate(5 minutes)
      - httpApi: { path: /api/sim/trigger, method: post }
